INSERT INTO "album" ("id", "genre_id", "artist_id", "title", "price") VALUES (386, 1, 1, 'For Those About To Rock We Salute You', CAST(8.99 AS Numeric(10, 2)));
INSERT INTO "album" ("id", "genre_id", "artist_id", "title", "price") VALUES (387, 1, 1, 'Let There Be Rock', CAST(8.99 AS Numeric(10, 2)));
INSERT INTO "album" ("id", "genre_id", "artist_id", "title", "price") VALUES (388, 1, 100, 'Greatest Hits', CAST(8.99 AS Numeric(10, 2)));
INSERT INTO "album" ("id", "genre_id", "artist_id", "title", "price") VALUES (389, 1, 102, 'Misplaced Childhood', CAST(8.99 AS Numeric(10, 2)));
INSERT INTO "album" ("id", "genre_id", "artist_id", "title", "price") VALUES (390, 1, 105, 'The Best Of Men At Work', CAST(8.99 AS Numeric(10, 2)));
INSERT INTO "album" ("id", "genre_id", "artist_id", "title", "price") VALUES (392, 1, 110, 'Nevermind', CAST(8.99 AS Numeric(10, 2)));
INSERT INTO "album" ("id", "genre_id", "artist_id", "title", "price") VALUES (393, 1, 111, 'Compositores', CAST(8.99 AS Numeric(10, 2)));
INSERT INTO "album" ("id", "genre_id", "artist_id", "title", "price") VALUES (394, 1, 114, 'Bark at the Moon (Remastered)', CAST(8.99 AS Numeric(10, 2)));
INSERT INTO "album" ("id", "genre_id", "artist_id", "title", "price") VALUES (395, 1, 114, 'Blizzard of Ozz', CAST(8.99 AS Numeric(10, 2)));
INSERT INTO "album" ("id", "genre_id", "artist_id", "title", "price") VALUES (396, 1, 114, 'Diary of a Madman (Remastered)', CAST(8.99 AS Numeric(10, 2)));
INSERT INTO "album" ("id", "genre_id", "artist_id", "title", "price") VALUES (397, 1, 114, 'No More Tears (Remastered)', CAST(8.99 AS Numeric(10, 2)));
INSERT INTO "album" ("id", "genre_id", "artist_id", "title", "price") VALUES (398, 1, 114, 'Speak of the Devil', CAST(8.99 AS Numeric(10, 2)));
INSERT INTO "album" ("id", "genre_id", "artist_id", "title", "price") VALUES (399, 1, 115, 'Walking Into Clarksdale', CAST(8.99 AS Numeric(10, 2)));
INSERT INTO "album" ("id", "genre_id", "artist_id", "title", "price") VALUES (400, 1, 117, 'The Beast Live', CAST(8.99 AS Numeric(10, 2)));
INSERT INTO "album" ("id", "genre_id", "artist_id", "title", "price") VALUES (401, 1, 118, 'Live On Two Legs "Live"', CAST(8.99 AS Numeric(10, 2)));
INSERT INTO "album" ("id", "genre_id", "artist_id", "title", "price") VALUES (402, 1, 118, 'Riot Act', CAST(8.99 AS Numeric(10, 2)));
INSERT INTO "album" ("id", "genre_id", "artist_id", "title", "price") VALUES (403, 1, 118, 'Te', CAST(8.99 AS Numeric(10, 2)));
INSERT INTO "album" ("id", "genre_id", "artist_id", "title", "price") VALUES (404, 1, 118, 'Vs.', CAST(8.99 AS Numeric(10, 2)));
INSERT INTO "album" ("id", "genre_id", "artist_id", "title", "price") VALUES (405, 1, 120, 'Dark Side Of The Moo', CAST(8.99 AS Numeric(10, 2)));
INSERT INTO "album" ("id", "genre_id", "artist_id", "title", "price") VALUES (406, 1, 124, 'New Adventures In Hi-Fi', CAST(8.99 AS Numeric(10, 2)));
INSERT INTO "album" ("id", "genre_id", "artist_id", "title", "price") VALUES (407, 1, 126, 'Raul Seixas', CAST(8.99 AS Numeric(10, 2)));
INSERT INTO "album" ("id", "genre_id", "artist_id", "title", "price") VALUES (408, 1, 127, 'By The Way', CAST(8.99 AS Numeric(10, 2)));
INSERT INTO "album" ("id", "genre_id", "artist_id", "title", "price") VALUES (409, 1, 127, 'Californicatio', CAST(8.99 AS Numeric(10, 2)));
INSERT INTO "album" ("id", "genre_id", "artist_id", "title", "price") VALUES (410, 1, 128, 'Retrospective I (1974-1980)', CAST(8.99 AS Numeric(10, 2)));
INSERT INTO "album" ("id", "genre_id", "artist_id", "title", "price") VALUES (411, 1, 130, 'Maquinarama', CAST(8.99 AS Numeric(10, 2)));
INSERT INTO "album" ("id", "genre_id", "artist_id", "title", "price") VALUES (412, 1, 130, 'O Samba Poconé', CAST(8.99 AS Numeric(10, 2)));
INSERT INTO "album" ("id", "genre_id", "artist_id", "title", "price") VALUES (413, 1, 132, 'A-Sides', CAST(8.99 AS Numeric(10, 2)));
INSERT INTO "album" ("id", "genre_id", "artist_id", "title", "price") VALUES (414, 1, 134, 'Core', CAST(8.99 AS Numeric(10, 2)));
INSERT INTO "album" ("id", "genre_id", "artist_id", "title", "price") VALUES (415, 1, 136, '"1997" Black Light Syndrome', CAST(8.99 AS Numeric(10, 2)));
INSERT INTO "album" ("id", "genre_id", "artist_id", "title", "price") VALUES (416, 1, 139, 'Beyond Good And Evil', CAST(8.99 AS Numeric(10, 2)));
INSERT INTO "album" ("id", "genre_id", "artist_id", "title", "price") VALUES (418, 1, 140, 'The Doors', CAST(8.99 AS Numeric(10, 2)));
INSERT INTO "album" ("id", "genre_id", "artist_id", "title", "price") VALUES (419, 1, 141, 'The Police Greatest Hits', CAST(8.99 AS Numeric(10, 2)));
INSERT INTO "album" ("id", "genre_id", "artist_id", "title", "price") VALUES (420, 1, 142, 'Hot Rocks, 1964-1971 (Disc 1)', CAST(8.99 AS Numeric(10, 2)));
INSERT INTO "album" ("id", "genre_id", "artist_id", "title", "price") VALUES (421, 1, 142, 'No Security', CAST(8.99 AS Numeric(10, 2)));
INSERT INTO "album" ("id", "genre_id", "artist_id", "title", "price") VALUES (422, 1, 142, 'Voodoo Lounge', CAST(8.99 AS Numeric(10, 2)));
INSERT INTO "album" ("id", "genre_id", "artist_id", "title", "price") VALUES (423, 1, 144, 'My Generation - The Very Best Of The Who', CAST(8.99 AS Numeric(10, 2)));
INSERT INTO "album" ("id", "genre_id", "artist_id", "title", "price") VALUES (424, 1, 150, 'Achtung Baby', CAST(8.99 AS Numeric(10, 2)));
INSERT INTO "album" ("id", "genre_id", "artist_id", "title", "price") VALUES (425, 1, 150, 'B-Sides 1980-1990', CAST(8.99 AS Numeric(10, 2)));
INSERT INTO "album" ("id", "genre_id", "artist_id", "title", "price") VALUES (426, 1, 150, 'How To Dismantle An Atomic Bomb', CAST(8.99 AS Numeric(10, 2)));
INSERT INTO "album" ("id", "genre_id", "artist_id", "title", "price") VALUES (427, 1, 150, 'Pop', CAST(8.99 AS Numeric(10, 2)));
INSERT INTO "album" ("id", "genre_id", "artist_id", "title", "price") VALUES (428, 1, 150, 'Rattle And Hum', CAST(8.99 AS Numeric(10, 2)));
INSERT INTO "album" ("id", "genre_id", "artist_id", "title", "price") VALUES (429, 1, 150, 'The Best Of 1980-1990', CAST(8.99 AS Numeric(10, 2)));
INSERT INTO "album" ("id", "genre_id", "artist_id", "title", "price") VALUES (430, 1, 150, 'War', CAST(8.99 AS Numeric(10, 2)));
INSERT INTO "album" ("id", "genre_id", "artist_id", "title", "price") VALUES (431, 1, 150, 'Zooropa', CAST(8.99 AS Numeric(10, 2)));
INSERT INTO "album" ("id", "genre_id", "artist_id", "title", "price") VALUES (432, 1, 152, 'Diver Dow', CAST(8.99 AS Numeric(10, 2)));
INSERT INTO "album" ("id", "genre_id", "artist_id", "title", "price") VALUES (433, 1, 152, 'The Best Of Van Halen, Vol. I', CAST(8.99 AS Numeric(10, 2)));
INSERT INTO "album" ("id", "genre_id", "artist_id", "title", "price") VALUES (434, 1, 152, 'Van Halen III', CAST(8.99 AS Numeric(10, 2)));
INSERT INTO "album" ("id", "genre_id", "artist_id", "title", "price") VALUES (435, 1, 152, 'Van Hale', CAST(8.99 AS Numeric(10, 2)));
INSERT INTO "album" ("id", "genre_id", "artist_id", "title", "price") VALUES (436, 1, 153, 'Contraband', CAST(8.99 AS Numeric(10, 2)));
INSERT INTO "album" ("id", "genre_id", "artist_id", "title", "price") VALUES (437, 1, 157, 'Un-Led-Ed', CAST(8.99 AS Numeric(10, 2)));
INSERT INTO "album" ("id", "genre_id", "artist_id", "title", "price") VALUES (439, 1, 2, 'Balls to the Wall', CAST(8.99 AS Numeric(10, 2)));
INSERT INTO "album" ("id", "genre_id", "artist_id", "title", "price") VALUES (440, 1, 2, 'Restless and Wild', CAST(8.99 AS Numeric(10, 2)));
INSERT INTO "album" ("id", "genre_id", "artist_id", "title", "price") VALUES (441, 1, 200, 'Every Kind of Light', CAST(8.99 AS Numeric(10, 2)));
INSERT INTO "album" ("id", "genre_id", "artist_id", "title", "price") VALUES (442, 1, 22, 'BBC Sessions "Disc 1" "Live"', CAST(8.99 AS Numeric(10, 2)));
INSERT INTO "album" ("id", "genre_id", "artist_id", "title", "price") VALUES (443, 1, 22, 'BBC Sessions "Disc 2" "Live"', CAST(8.99 AS Numeric(10, 2)));
INSERT INTO "album" ("id", "genre_id", "artist_id", "title", "price") VALUES (444, 1, 22, 'Coda', CAST(8.99 AS Numeric(10, 2)));
INSERT INTO "album" ("id", "genre_id", "artist_id", "title", "price") VALUES (445, 1, 22, 'Houses Of The Holy', CAST(8.99 AS Numeric(10, 2)));
INSERT INTO "album" ("id", "genre_id", "artist_id", "title", "price") VALUES (446, 1, 22, 'In Through The Out Door', CAST(8.99 AS Numeric(10, 2)));
INSERT INTO "album" ("id", "genre_id", "artist_id", "title", "price") VALUES (447, 1, 22, 'IV', CAST(8.99 AS Numeric(10, 2)));
INSERT INTO "album" ("id", "genre_id", "artist_id", "title", "price") VALUES (448, 1, 22, 'Led Zeppelin I', CAST(8.99 AS Numeric(10, 2)));
INSERT INTO "album" ("id", "genre_id", "artist_id", "title", "price") VALUES (449, 1, 22, 'Led Zeppelin II', CAST(8.99 AS Numeric(10, 2)));
INSERT INTO "album" ("id", "genre_id", "artist_id", "title", "price") VALUES (450, 1, 22, 'Led Zeppelin III', CAST(8.99 AS Numeric(10, 2)));
INSERT INTO "album" ("id", "genre_id", "artist_id", "title", "price") VALUES (451, 1, 22, 'Physical Graffiti "Disc 1"', CAST(8.99 AS Numeric(10, 2)));
INSERT INTO "album" ("id", "genre_id", "artist_id", "title", "price") VALUES (452, 1, 22, 'Physical Graffiti "Disc 2"', CAST(8.99 AS Numeric(10, 2)));
INSERT INTO "album" ("id", "genre_id", "artist_id", "title", "price") VALUES (453, 1, 22, 'Presence', CAST(8.99 AS Numeric(10, 2)));
INSERT INTO "album" ("id", "genre_id", "artist_id", "title", "price") VALUES (454, 1, 22, 'The Song Remains The Same (Disc 1)', CAST(8.99 AS Numeric(10, 2)));
INSERT INTO "album" ("id", "genre_id", "artist_id", "title", "price") VALUES (455, 1, 22, 'The Song Remains The Same (Disc 2)', CAST(8.99 AS Numeric(10, 2)));
INSERT INTO "album" ("id", "genre_id", "artist_id", "title", "price") VALUES (456, 1, 23, 'Bongo Fury', CAST(8.99 AS Numeric(10, 2)));
INSERT INTO "album" ("id", "genre_id", "artist_id", "title", "price") VALUES (457, 1, 3, 'Big Ones', CAST(8.99 AS Numeric(10, 2)));
INSERT INTO "album" ("id", "genre_id", "artist_id", "title", "price") VALUES (458, 1, 4, 'Jagged Little Pill', CAST(8.99 AS Numeric(10, 2)));
INSERT INTO "album" ("id", "genre_id", "artist_id", "title", "price") VALUES (459, 1, 5, 'Facelift', CAST(8.99 AS Numeric(10, 2)));
INSERT INTO "album" ("id", "genre_id", "artist_id", "title", "price") VALUES (460, 1, 51, 'Greatest Hits I', CAST(8.99 AS Numeric(10, 2)));
INSERT INTO "album" ("id", "genre_id", "artist_id", "title", "price") VALUES (461, 1, 51, 'Greatest Hits II', CAST(8.99 AS Numeric(10, 2)));
INSERT INTO "album" ("id", "genre_id", "artist_id", "title", "price") VALUES (462, 1, 51, 'News Of The World', CAST(8.99 AS Numeric(10, 2)));
INSERT INTO "album" ("id", "genre_id", "artist_id", "title", "price") VALUES (463, 1, 52, 'Greatest Kiss', CAST(8.99 AS Numeric(10, 2)));
INSERT INTO "album" ("id", "genre_id", "artist_id", "title", "price") VALUES (464, 1, 52, 'Unplugged "Live"', CAST(8.99 AS Numeric(10, 2)));
INSERT INTO "album" ("id", "genre_id", "artist_id", "title", "price") VALUES (465, 1, 55, 'Into The Light', CAST(8.99 AS Numeric(10, 2)));
INSERT INTO "album" ("id", "genre_id", "artist_id", "title", "price") VALUES (466, 1, 58, 'Come Taste The Band', CAST(8.99 AS Numeric(10, 2)));
INSERT INTO "album" ("id", "genre_id", "artist_id", "title", "price") VALUES (467, 1, 58, 'Deep Purple In Rock', CAST(8.99 AS Numeric(10, 2)));
INSERT INTO "album" ("id", "genre_id", "artist_id", "title", "price") VALUES (468, 1, 58, 'Fireball', CAST(8.99 AS Numeric(10, 2)));
INSERT INTO "album" ("id", "genre_id", "artist_id", "title", "price") VALUES (469, 1, 58, 'Machine Head', CAST(8.99 AS Numeric(10, 2)));
INSERT INTO "album" ("id", "genre_id", "artist_id", "title", "price") VALUES (470, 1, 58, 'MK III The Final Concerts "Disc 1"', CAST(8.99 AS Numeric(10, 2)));
INSERT INTO "album" ("id", "genre_id", "artist_id", "title", "price") VALUES (471, 1, 58, 'Purpendicular', CAST(8.99 AS Numeric(10, 2)));
INSERT INTO "album" ("id", "genre_id", "artist_id", "title", "price") VALUES (472, 1, 58, 'Slaves And Masters', CAST(8.99 AS Numeric(10, 2)));
INSERT INTO "album" ("id", "genre_id", "artist_id", "title", "price") VALUES (473, 1, 58, 'Stormbringer', CAST(8.99 AS Numeric(10, 2)));
INSERT INTO "album" ("id", "genre_id", "artist_id", "title", "price") VALUES (474, 1, 58, 'The Battle Rages O', CAST(8.99 AS Numeric(10, 2)));
INSERT INTO "album" ("id", "genre_id", "artist_id", "title", "price") VALUES (475, 1, 58, 'The Final Concerts (Disc 2)', CAST(8.99 AS Numeric(10, 2)));
INSERT INTO "album" ("id", "genre_id", "artist_id", "title", "price") VALUES (476, 1, 59, 'Santana - As Years Go By', CAST(8.99 AS Numeric(10, 2)));
INSERT INTO "album" ("id", "genre_id", "artist_id", "title", "price") VALUES (477, 1, 59, 'Santana Live', CAST(8.99 AS Numeric(10, 2)));
INSERT INTO "album" ("id", "genre_id", "artist_id", "title", "price") VALUES (478, 1, 59, 'Supernatural', CAST(8.99 AS Numeric(10, 2)));
INSERT INTO "album" ("id", "genre_id", "artist_id", "title", "price") VALUES (479, 1, 76, 'Chronicle, Vol. 1', CAST(8.99 AS Numeric(10, 2)));
INSERT INTO "album" ("id", "genre_id", "artist_id", "title", "price") VALUES (480, 1, 76, 'Chronicle, Vol. 2', CAST(8.99 AS Numeric(10, 2)));
INSERT INTO "album" ("id", "genre_id", "artist_id", "title", "price") VALUES (481, 1, 8, 'Audioslave', CAST(8.99 AS Numeric(10, 2)));
INSERT INTO "album" ("id", "genre_id", "artist_id", "title", "price") VALUES (482, 1, 82, 'King For A Day Fool For A Lifetime', CAST(8.99 AS Numeric(10, 2)));
INSERT INTO "album" ("id", "genre_id", "artist_id", "title", "price") VALUES (483, 1, 84, 'In Your Honor "Disc 1"', CAST(8.99 AS Numeric(10, 2)));
INSERT INTO "album" ("id", "genre_id", "artist_id", "title", "price") VALUES (484, 1, 84, 'In Your Honor "Disc 2"', CAST(8.99 AS Numeric(10, 2)));
INSERT INTO "album" ("id", "genre_id", "artist_id", "title", "price") VALUES (485, 1, 84, 'The Colour And The Shape', CAST(8.99 AS Numeric(10, 2)));
INSERT INTO "album" ("id", "genre_id", "artist_id", "title", "price") VALUES (486, 1, 88, 'Appetite for Destructio', CAST(8.99 AS Numeric(10, 2)));
INSERT INTO "album" ("id", "genre_id", "artist_id", "title", "price") VALUES (487, 1, 88, 'Use Your Illusion I', CAST(8.99 AS Numeric(10, 2)));
INSERT INTO "album" ("id", "genre_id", "artist_id", "title", "price") VALUES (488, 1, 90, 'A Matter of Life and Death', CAST(8.99 AS Numeric(10, 2)));
INSERT INTO "album" ("id", "genre_id", "artist_id", "title", "price") VALUES (489, 1, 90, 'Brave New World', CAST(8.99 AS Numeric(10, 2)));
INSERT INTO "album" ("id", "genre_id", "artist_id", "title", "price") VALUES (490, 1, 90, 'Fear Of The Dark', CAST(8.99 AS Numeric(10, 2)));
INSERT INTO "album" ("id", "genre_id", "artist_id", "title", "price") VALUES (491, 1, 90, 'Live At Donington 1992 (Disc 1)', CAST(8.99 AS Numeric(10, 2)));
INSERT INTO "album" ("id", "genre_id", "artist_id", "title", "price") VALUES (492, 1, 90, 'Live At Donington 1992 (Disc 2)', CAST(8.99 AS Numeric(10, 2)));
INSERT INTO "album" ("id", "genre_id", "artist_id", "title", "price") VALUES (493, 1, 90, 'Rock In Rio "CD2"', CAST(8.99 AS Numeric(10, 2)));
INSERT INTO "album" ("id", "genre_id", "artist_id", "title", "price") VALUES (494, 1, 90, 'The Number of The Beast', CAST(8.99 AS Numeric(10, 2)));
INSERT INTO "album" ("id", "genre_id", "artist_id", "title", "price") VALUES (495, 1, 90, 'The X Factor', CAST(8.99 AS Numeric(10, 2)));
INSERT INTO "album" ("id", "genre_id", "artist_id", "title", "price") VALUES (496, 1, 90, 'Virtual XI', CAST(8.99 AS Numeric(10, 2)));
INSERT INTO "album" ("id", "genre_id", "artist_id", "title", "price") VALUES (497, 1, 92, 'Emergency On Planet Earth', CAST(8.99 AS Numeric(10, 2)));
INSERT INTO "album" ("id", "genre_id", "artist_id", "title", "price") VALUES (498, 1, 94, 'Are You Experienced?', CAST(8.99 AS Numeric(10, 2)));
INSERT INTO "album" ("id", "genre_id", "artist_id", "title", "price") VALUES (499, 1, 95, 'Surfing with the Alien (Remastered)', CAST(8.99 AS Numeric(10, 2)));
INSERT INTO "album" ("id", "genre_id", "artist_id", "title", "price") VALUES (500, 10, 203, 'The Best of Beethove', CAST(8.99 AS Numeric(10, 2)));
INSERT INTO "album" ("id", "genre_id", "artist_id", "title", "price") VALUES (504, 10, 208, 'Pachelbel: Canon & Gigue', CAST(8.99 AS Numeric(10, 2)));
INSERT INTO "album" ("id", "genre_id", "artist_id", "title", "price") VALUES (507, 10, 211, 'Bach: Goldberg Variations', CAST(8.99 AS Numeric(10, 2)));
INSERT INTO "album" ("id", "genre_id", "artist_id", "title", "price") VALUES (508, 10, 212, 'Bach: The Cello Suites', CAST(8.99 AS Numeric(10, 2)));
INSERT INTO "album" ("id", "genre_id", "artist_id", "title", "price") VALUES (509, 10, 213, 'Handel: The Messiah (Highlights)', CAST(8.99 AS Numeric(10, 2)));
INSERT INTO "album" ("id", "genre_id", "artist_id", "title", "price") VALUES (513, 10, 217, 'Haydn: Symphonies 99 - 104', CAST(8.99 AS Numeric(10, 2)));
INSERT INTO "album" ("id", "genre_id", "artist_id", "title", "price") VALUES (515, 10, 219, 'A Soprano Inspired', CAST(8.99 AS Numeric(10, 2)));
INSERT INTO "album" ("id", "genre_id", "artist_id", "title", "price") VALUES (517, 10, 221, 'Wagner: Favourite Overtures', CAST(8.99 AS Numeric(10, 2)));
INSERT INTO "album" ("id", "genre_id", "artist_id", "title", "price") VALUES (519, 10, 223, 'Tchaikovsky: The Nutcracker', CAST(8.99 AS Numeric(10, 2)));
INSERT INTO "album" ("id", "genre_id", "artist_id", "title", "price") VALUES (520, 10, 224, 'The Last Night of the Proms', CAST(8.99 AS Numeric(10, 2)));
INSERT INTO "album" ("id", "genre_id", "artist_id", "title", "price") VALUES (523, 10, 226, 'Respighi:Pines of Rome', CAST(8.99 AS Numeric(10, 2)));
INSERT INTO "album" ("id", "genre_id", "artist_id", "title", "price") VALUES (524, 10, 226, 'Strauss: Waltzes', CAST(8.99 AS Numeric(10, 2)));
INSERT INTO "album" ("id", "genre_id", "artist_id", "title", "price") VALUES (525, 10, 229, 'Carmina Burana', CAST(8.99 AS Numeric(10, 2)));
INSERT INTO "album" ("id", "genre_id", "artist_id", "title", "price") VALUES (526, 10, 230, 'A Copland Celebration, Vol. I', CAST(8.99 AS Numeric(10, 2)));
INSERT INTO "album" ("id", "genre_id", "artist_id", "title", "price") VALUES (527, 10, 231, 'Bach: Toccata & Fugue in D Minor', CAST(8.99 AS Numeric(10, 2)));
INSERT INTO "album" ("id", "genre_id", "artist_id", "title", "price") VALUES (528, 10, 232, 'Prokofiev: Symphony No.1', CAST(8.99 AS Numeric(10, 2)));
INSERT INTO "album" ("id", "genre_id", "artist_id", "title", "price") VALUES (529, 10, 233, 'Scheherazade', CAST(8.99 AS Numeric(10, 2)));
INSERT INTO "album" ("id", "genre_id", "artist_id", "title", "price") VALUES (530, 10, 234, 'Bach: The Brandenburg Concertos', CAST(8.99 AS Numeric(10, 2)));
INSERT INTO "album" ("id", "genre_id", "artist_id", "title", "price") VALUES (532, 10, 236, 'Mascagni: Cavalleria Rusticana', CAST(8.99 AS Numeric(10, 2)));
INSERT INTO "album" ("id", "genre_id", "artist_id", "title", "price") VALUES (533, 10, 237, 'Sibelius: Finlandia', CAST(8.99 AS Numeric(10, 2)));
INSERT INTO "album" ("id", "genre_id", "artist_id", "title", "price") VALUES (537, 10, 242, 'Adams, John: The Chairman Dances', CAST(8.99 AS Numeric(10, 2)));
INSERT INTO "album" ("id", "genre_id", "artist_id", "title", "price") VALUES (539, 10, 245, 'Berlioz: Symphonie Fantastique', CAST(8.99 AS Numeric(10, 2)));
INSERT INTO "album" ("id", "genre_id", "artist_id", "title", "price") VALUES (540, 10, 245, 'Prokofiev: Romeo & Juliet', CAST(8.99 AS Numeric(10, 2)));
INSERT INTO "album" ("id", "genre_id", "artist_id", "title", "price") VALUES (542, 10, 247, 'English Renaissance', CAST(8.99 AS Numeric(10, 2)));
INSERT INTO "album" ("id", "genre_id", "artist_id", "title", "price") VALUES (544, 10, 248, 'Mozart: Symphonies Nos. 40 & 41', CAST(8.99 AS Numeric(10, 2)));
INSERT INTO "album" ("id", "genre_id", "artist_id", "title", "price") VALUES (546, 10, 250, 'SCRIABIN: Vers la flamme', CAST(8.99 AS Numeric(10, 2)));
INSERT INTO "album" ("id", "genre_id", "artist_id", "title", "price") VALUES (548, 10, 255, 'Bartok: Violin & Viola Concertos', CAST(8.99 AS Numeric(10, 2)));
INSERT INTO "album" ("id", "genre_id", "artist_id", "title", "price") VALUES (551, 10, 259, 'South American Getaway', CAST(8.99 AS Numeric(10, 2)));
INSERT INTO "album" ("id", "genre_id", "artist_id", "title", "price") VALUES (552, 10, 260, 'Górecki: Symphony No. 3', CAST(8.99 AS Numeric(10, 2)));
INSERT INTO "album" ("id", "genre_id", "artist_id", "title", "price") VALUES (553, 10, 261, 'Purcell: The Fairy Quee', CAST(8.99 AS Numeric(10, 2)));
INSERT INTO "album" ("id", "genre_id", "artist_id", "title", "price") VALUES (556, 10, 264, 'Weill: The Seven Deadly Sins', CAST(8.99 AS Numeric(10, 2)));
INSERT INTO "album" ("id", "genre_id", "artist_id", "title", "price") VALUES (558, 10, 266, 'Szymanowski: Piano Works, Vol. 1', CAST(8.99 AS Numeric(10, 2)));
INSERT INTO "album" ("id", "genre_id", "artist_id", "title", "price") VALUES (559, 10, 267, 'Nielsen: The Six Symphonies', CAST(8.99 AS Numeric(10, 2)));
INSERT INTO "album" ("id", "genre_id", "artist_id", "title", "price") VALUES (562, 10, 274, 'Mozart: Chamber Music', CAST(8.99 AS Numeric(10, 2)));
INSERT INTO "album" ("id", "genre_id", "artist_id", "title", "price") VALUES (563, 2, 10, 'The Best Of Billy Cobham', CAST(8.99 AS Numeric(10, 2)));
INSERT INTO "album" ("id", "genre_id", "artist_id", "title", "price") VALUES (564, 2, 197, 'Quiet Songs', CAST(8.99 AS Numeric(10, 2)));
INSERT INTO "album" ("id", "genre_id", "artist_id", "title", "price") VALUES (565, 2, 202, 'Worlds', CAST(8.99 AS Numeric(10, 2)));
INSERT INTO "album" ("id", "genre_id", "artist_id", "title", "price") VALUES (566, 2, 27, 'Quanta Gente Veio ver--Bônus De Carnaval', CAST(8.99 AS Numeric(10, 2)));
INSERT INTO "album" ("id", "genre_id", "artist_id", "title", "price") VALUES (567, 2, 53, 'Heart of the Night', CAST(8.99 AS Numeric(10, 2)));
INSERT INTO "album" ("id", "genre_id", "artist_id", "title", "price") VALUES (568, 2, 53, 'Morning Dance', CAST(8.99 AS Numeric(10, 2)));
INSERT INTO "album" ("id", "genre_id", "artist_id", "title", "price") VALUES (569, 2, 6, 'Warner 25 Anos', CAST(8.99 AS Numeric(10, 2)));
INSERT INTO "album" ("id", "genre_id", "artist_id", "title", "price") VALUES (570, 2, 68, 'Miles Ahead', CAST(8.99 AS Numeric(10, 2)));
INSERT INTO "album" ("id", "genre_id", "artist_id", "title", "price") VALUES (571, 2, 68, 'The Essential Miles Davis "Disc 1"', CAST(8.99 AS Numeric(10, 2)));
INSERT INTO "album" ("id", "genre_id", "artist_id", "title", "price") VALUES (572, 2, 68, 'The Essential Miles Davis "Disc 2"', CAST(8.99 AS Numeric(10, 2)));
INSERT INTO "album" ("id", "genre_id", "artist_id", "title", "price") VALUES (573, 2, 79, 'Outbreak', CAST(8.99 AS Numeric(10, 2)));
INSERT INTO "album" ("id", "genre_id", "artist_id", "title", "price") VALUES (574, 2, 89, 'Blue Moods', CAST(8.99 AS Numeric(10, 2)));
INSERT INTO "album" ("id", "genre_id", "artist_id", "title", "price") VALUES (575, 3, 100, 'Greatest Hits', CAST(8.99 AS Numeric(10, 2)));
INSERT INTO "album" ("id", "genre_id", "artist_id", "title", "price") VALUES (576, 3, 106, 'Ace Of Spades', CAST(8.99 AS Numeric(10, 2)));
INSERT INTO "album" ("id", "genre_id", "artist_id", "title", "price") VALUES (577, 3, 109, 'Motley Crue Greatest Hits', CAST(8.99 AS Numeric(10, 2)));
INSERT INTO "album" ("id", "genre_id", "artist_id", "title", "price") VALUES (578, 3, 11, 'Alcohol Fueled Brewtality Live! "Disc 1"', CAST(8.99 AS Numeric(10, 2)));
INSERT INTO "album" ("id", "genre_id", "artist_id", "title", "price") VALUES (579, 3, 11, 'Alcohol Fueled Brewtality Live! "Disc 2"', CAST(8.99 AS Numeric(10, 2)));
INSERT INTO "album" ("id", "genre_id", "artist_id", "title", "price") VALUES (580, 3, 114, 'Tribute', CAST(8.99 AS Numeric(10, 2)));
INSERT INTO "album" ("id", "genre_id", "artist_id", "title", "price") VALUES (581, 3, 12, 'Black Sabbath Vol. 4 (Remaster)', CAST(8.99 AS Numeric(10, 2)));
INSERT INTO "album" ("id", "genre_id", "artist_id", "title", "price") VALUES (582, 3, 12, 'Black Sabbath', CAST(8.99 AS Numeric(10, 2)));
INSERT INTO "album" ("id", "genre_id", "artist_id", "title", "price") VALUES (583, 3, 135, 'Mezmerize', CAST(8.99 AS Numeric(10, 2)));
INSERT INTO "album" ("id", "genre_id", "artist_id", "title", "price") VALUES (584, 3, 14, 'Chemical Wedding', CAST(8.99 AS Numeric(10, 2)));
INSERT INTO "album" ("id", "genre_id", "artist_id", "title", "price") VALUES (585, 3, 50, '...And Justice For All', CAST(8.99 AS Numeric(10, 2)));
INSERT INTO "album" ("id", "genre_id", "artist_id", "title", "price") VALUES (586, 3, 50, 'Black album', CAST(8.99 AS Numeric(10, 2)));
INSERT INTO "album" ("id", "genre_id", "artist_id", "title", "price") VALUES (587, 3, 50, 'Garage Inc. (Disc 1)', CAST(8.99 AS Numeric(10, 2)));
INSERT INTO "album" ("id", "genre_id", "artist_id", "title", "price") VALUES (588, 3, 50, 'Garage Inc. (Disc 2)', CAST(8.99 AS Numeric(10, 2)));
INSERT INTO "album" ("id", "genre_id", "artist_id", "title", "price") VALUES (589, 3, 50, 'Load', CAST(8.99 AS Numeric(10, 2)));
INSERT INTO "album" ("id", "genre_id", "artist_id", "title", "price") VALUES (590, 3, 50, 'Master Of Puppets', CAST(8.99 AS Numeric(10, 2)));
INSERT INTO "album" ("id", "genre_id", "artist_id", "title", "price") VALUES (591, 3, 50, 'ReLoad', CAST(8.99 AS Numeric(10, 2)));
INSERT INTO "album" ("id", "genre_id", "artist_id", "title", "price") VALUES (592, 3, 50, 'Ride The Lightning', CAST(8.99 AS Numeric(10, 2)));
INSERT INTO "album" ("id", "genre_id", "artist_id", "title", "price") VALUES (593, 3, 50, 'St. Anger', CAST(8.99 AS Numeric(10, 2)));
INSERT INTO "album" ("id", "genre_id", "artist_id", "title", "price") VALUES (594, 3, 7, 'Plays Metallica By Four Cellos', CAST(8.99 AS Numeric(10, 2)));
INSERT INTO "album" ("id", "genre_id", "artist_id", "title", "price") VALUES (595, 3, 87, 'Faceless', CAST(8.99 AS Numeric(10, 2)));
INSERT INTO "album" ("id", "genre_id", "artist_id", "title", "price") VALUES (596, 3, 88, 'Use Your Illusion II', CAST(8.99 AS Numeric(10, 2)));
INSERT INTO "album" ("id", "genre_id", "artist_id", "title", "price") VALUES (597, 3, 90, 'A Real Dead One', CAST(8.99 AS Numeric(10, 2)));
INSERT INTO "album" ("id", "genre_id", "artist_id", "title", "price") VALUES (598, 3, 90, 'A Real Live One', CAST(8.99 AS Numeric(10, 2)));
INSERT INTO "album" ("id", "genre_id", "artist_id", "title", "price") VALUES (599, 3, 90, 'Live After Death', CAST(8.99 AS Numeric(10, 2)));
INSERT INTO "album" ("id", "genre_id", "artist_id", "title", "price") VALUES (600, 3, 90, 'No Prayer For The Dying', CAST(8.99 AS Numeric(10, 2)));
INSERT INTO "album" ("id", "genre_id", "artist_id", "title", "price") VALUES (601, 3, 90, 'Piece Of Mind', CAST(8.99 AS Numeric(10, 2)));
INSERT INTO "album" ("id", "genre_id", "artist_id", "title", "price") VALUES (602, 3, 90, 'Powerslave', CAST(8.99 AS Numeric(10, 2)));
INSERT INTO "album" ("id", "genre_id", "artist_id", "title", "price") VALUES (603, 3, 90, 'Rock In Rio "CD1"', CAST(8.99 AS Numeric(10, 2)));
INSERT INTO "album" ("id", "genre_id", "artist_id", "title", "price") VALUES (604, 3, 90, 'Rock In Rio "CD2"', CAST(8.99 AS Numeric(10, 2)));
INSERT INTO "album" ("id", "genre_id", "artist_id", "title", "price") VALUES (605, 3, 90, 'Seventh Son of a Seventh So', CAST(8.99 AS Numeric(10, 2)));
INSERT INTO "album" ("id", "genre_id", "artist_id", "title", "price") VALUES (606, 3, 90, 'Somewhere in Time', CAST(8.99 AS Numeric(10, 2)));
INSERT INTO "album" ("id", "genre_id", "artist_id", "title", "price") VALUES (607, 3, 90, 'The Number of The Beast', CAST(8.99 AS Numeric(10, 2)));
INSERT INTO "album" ("id", "genre_id", "artist_id", "title", "price") VALUES (608, 3, 98, 'Living After Midnight', CAST(8.99 AS Numeric(10, 2)));
INSERT INTO "album" ("id", "genre_id", "artist_id", "title", "price") VALUES (609, 4, 196, 'Cake: B-Sides and Rarities', CAST(8.99 AS Numeric(10, 2)));
INSERT INTO "album" ("id", "genre_id", "artist_id", "title", "price") VALUES (610, 4, 204, 'Temple of the Dog', CAST(8.99 AS Numeric(10, 2)));
INSERT INTO "album" ("id", "genre_id", "artist_id", "title", "price") VALUES (611, 4, 205, 'Carry O', CAST(8.99 AS Numeric(10, 2)));
INSERT INTO "album" ("id", "genre_id", "artist_id", "title", "price") VALUES (612, 4, 253, 'Carried to Dust (Bonus Track Version)', CAST(8.99 AS Numeric(10, 2)));
INSERT INTO "album" ("id", "genre_id", "artist_id", "title", "price") VALUES (613, 4, 8, 'Revelations', CAST(8.99 AS Numeric(10, 2)));
INSERT INTO "album" ("id", "genre_id", "artist_id", "title", "price") VALUES (614, 6, 133, 'In Step', CAST(8.99 AS Numeric(10, 2)));
INSERT INTO "album" ("id", "genre_id", "artist_id", "title", "price") VALUES (615, 6, 137, 'Live "Disc 1"', CAST(8.99 AS Numeric(10, 2)));
INSERT INTO "album" ("id", "genre_id", "artist_id", "title", "price") VALUES (616, 6, 137, 'Live "Disc 2"', CAST(8.99 AS Numeric(10, 2)));
INSERT INTO "album" ("id", "genre_id", "artist_id", "title", "price") VALUES (618, 6, 81, 'The Cream Of Clapto', CAST(8.99 AS Numeric(10, 2)));
INSERT INTO "album" ("id", "genre_id", "artist_id", "title", "price") VALUES (619, 6, 81, 'Unplugged', CAST(8.99 AS Numeric(10, 2)));
INSERT INTO "album" ("id", "genre_id", "artist_id", "title", "price") VALUES (620, 6, 90, 'Iron Maide', CAST(8.99 AS Numeric(10, 2)));
INSERT INTO "album" ("id", "genre_id", "artist_id", "title", "price") VALUES (623, 7, 103, 'Barulhinho Bom', CAST(8.99 AS Numeric(10, 2)));
INSERT INTO "album" ("id", "genre_id", "artist_id", "title", "price") VALUES (624, 7, 112, 'Olodum', CAST(8.99 AS Numeric(10, 2)));
INSERT INTO "album" ("id", "genre_id", "artist_id", "title", "price") VALUES (625, 7, 113, 'Acústico MTV', CAST(8.99 AS Numeric(10, 2)));
INSERT INTO "album" ("id", "genre_id", "artist_id", "title", "price") VALUES (626, 7, 113, 'Arquivo II', CAST(8.99 AS Numeric(10, 2)));
INSERT INTO "album" ("id", "genre_id", "artist_id", "title", "price") VALUES (627, 7, 113, 'Arquivo Os Paralamas Do Sucesso', CAST(8.99 AS Numeric(10, 2)));
INSERT INTO "album" ("id", "genre_id", "artist_id", "title", "price") VALUES (628, 7, 145, 'Serie Sem Limite (Disc 1)', CAST(8.99 AS Numeric(10, 2)));
INSERT INTO "album" ("id", "genre_id", "artist_id", "title", "price") VALUES (629, 7, 145, 'Serie Sem Limite (Disc 2)', CAST(8.99 AS Numeric(10, 2)));
INSERT INTO "album" ("id", "genre_id", "artist_id", "title", "price") VALUES (630, 7, 155, 'Ao Vivo "IMPORT"', CAST(8.99 AS Numeric(10, 2)));
INSERT INTO "album" ("id", "genre_id", "artist_id", "title", "price") VALUES (631, 7, 16, 'Prenda Minha', CAST(8.99 AS Numeric(10, 2)));
INSERT INTO "album" ("id", "genre_id", "artist_id", "title", "price") VALUES (632, 7, 16, 'Sozinho Remix Ao Vivo', CAST(8.99 AS Numeric(10, 2)));
INSERT INTO "album" ("id", "genre_id", "artist_id", "title", "price") VALUES (633, 7, 17, 'Minha Historia', CAST(8.99 AS Numeric(10, 2)));
INSERT INTO "album" ("id", "genre_id", "artist_id", "title", "price") VALUES (634, 7, 18, 'Afrociberdelia', CAST(8.99 AS Numeric(10, 2)));
INSERT INTO "album" ("id", "genre_id", "artist_id", "title", "price") VALUES (635, 7, 18, 'Da Lama Ao Caos', CAST(8.99 AS Numeric(10, 2)));
INSERT INTO "album" ("id", "genre_id", "artist_id", "title", "price") VALUES (636, 7, 20, 'Na Pista', CAST(8.99 AS Numeric(10, 2)));
INSERT INTO "album" ("id", "genre_id", "artist_id", "title", "price") VALUES (637, 7, 201, 'Duos II', CAST(8.99 AS Numeric(10, 2)));
INSERT INTO "album" ("id", "genre_id", "artist_id", "title", "price") VALUES (638, 7, 21, 'Sambas De Enredo 2001', CAST(8.99 AS Numeric(10, 2)));
INSERT INTO "album" ("id", "genre_id", "artist_id", "title", "price") VALUES (639, 7, 21, 'Vozes do MPB', CAST(8.99 AS Numeric(10, 2)));
INSERT INTO "album" ("id", "genre_id", "artist_id", "title", "price") VALUES (640, 7, 24, 'Chill: Brazil (Disc 1)', CAST(8.99 AS Numeric(10, 2)));
INSERT INTO "album" ("id", "genre_id", "artist_id", "title", "price") VALUES (641, 7, 27, 'Quanta Gente Veio Ver (Live)', CAST(8.99 AS Numeric(10, 2)));
INSERT INTO "album" ("id", "genre_id", "artist_id", "title", "price") VALUES (642, 7, 37, 'The Best of Ed Motta', CAST(8.99 AS Numeric(10, 2)));
INSERT INTO "album" ("id", "genre_id", "artist_id", "title", "price") VALUES (643, 7, 41, 'Elis Regina-Minha História', CAST(8.99 AS Numeric(10, 2)));
INSERT INTO "album" ("id", "genre_id", "artist_id", "title", "price") VALUES (644, 7, 42, 'Milton Nascimento Ao Vivo', CAST(8.99 AS Numeric(10, 2)));
INSERT INTO "album" ("id", "genre_id", "artist_id", "title", "price") VALUES (645, 7, 42, 'Minas', CAST(8.99 AS Numeric(10, 2)));
INSERT INTO "album" ("id", "genre_id", "artist_id", "title", "price") VALUES (646, 7, 46, 'Jorge Ben Jor 25 Anos', CAST(8.99 AS Numeric(10, 2)));
INSERT INTO "album" ("id", "genre_id", "artist_id", "title", "price") VALUES (647, 7, 56, 'Meus Momentos', CAST(8.99 AS Numeric(10, 2)));
INSERT INTO "album" ("id", "genre_id", "artist_id", "title", "price") VALUES (648, 7, 6, 'Chill: Brazil (Disc 2)', CAST(8.99 AS Numeric(10, 2)));
INSERT INTO "album" ("id", "genre_id", "artist_id", "title", "price") VALUES (649, 7, 72, 'Vinicius De Moraes', CAST(8.99 AS Numeric(10, 2)));
INSERT INTO "album" ("id", "genre_id", "artist_id", "title", "price") VALUES (651, 7, 77, 'Cássia Eller - Sem Limite "Disc 1"', CAST(8.99 AS Numeric(10, 2)));
INSERT INTO "album" ("id", "genre_id", "artist_id", "title", "price") VALUES (652, 7, 80, 'Djavan Ao Vivo - Vol. 02', CAST(8.99 AS Numeric(10, 2)));
INSERT INTO "album" ("id", "genre_id", "artist_id", "title", "price") VALUES (653, 7, 80, 'Djavan Ao Vivo - Vol. 1', CAST(8.99 AS Numeric(10, 2)));
INSERT INTO "album" ("id", "genre_id", "artist_id", "title", "price") VALUES (654, 7, 81, 'Unplugged', CAST(8.99 AS Numeric(10, 2)));
INSERT INTO "album" ("id", "genre_id", "artist_id", "title", "price") VALUES (655, 7, 83, 'Deixa Entrar', CAST(8.99 AS Numeric(10, 2)));
INSERT INTO "album" ("id", "genre_id", "artist_id", "title", "price") VALUES (656, 7, 86, 'Roda De Funk', CAST(8.99 AS Numeric(10, 2)));
INSERT INTO "album" ("id", "genre_id", "artist_id", "title", "price") VALUES (657, 7, 96, 'Jota Quest-1995', CAST(8.99 AS Numeric(10, 2)));
INSERT INTO "album" ("id", "genre_id", "artist_id", "title", "price") VALUES (659, 7, 99, 'Mais Do Mesmo', CAST(8.99 AS Numeric(10, 2)));
INSERT INTO "album" ("id", "genre_id", "artist_id", "title", "price") VALUES (660, 8, 100, 'Greatest Hits', CAST(8.99 AS Numeric(10, 2)));
INSERT INTO "album" ("id", "genre_id", "artist_id", "title", "price") VALUES (661, 8, 151, 'UB40 The Best Of - Volume Two "UK"', CAST(8.99 AS Numeric(10, 2)));
INSERT INTO "album" ("id", "genre_id", "artist_id", "title", "price") VALUES (662, 8, 19, 'Acústico MTV "Live"', CAST(8.99 AS Numeric(10, 2)));
INSERT INTO "album" ("id", "genre_id", "artist_id", "title", "price") VALUES (663, 8, 19, 'Cidade Negra - Hits', CAST(8.99 AS Numeric(10, 2)));
INSERT INTO "album" ("id", "genre_id", "artist_id", "title", "price") VALUES (665, 9, 21, 'Axé Bahia 2001', CAST(8.99 AS Numeric(10, 2)));
INSERT INTO "album" ("id", "genre_id", "artist_id", "title", "price") VALUES (666, 9, 252, 'Frank', CAST(8.99 AS Numeric(10, 2)));
INSERT INTO "album" ("id", "genre_id", "artist_id", "title", "price") VALUES (667, 5, 276, 'Le Freak', CAST(8.99 AS Numeric(10, 2)));
INSERT INTO "album" ("id", "genre_id", "artist_id", "title", "price") VALUES (668, 5, 278, 'MacArthur Park Suite', CAST(8.99 AS Numeric(10, 2)));
INSERT INTO "album" ("id", "genre_id", "artist_id", "title", "price") VALUES (669, 5, 277, 'Ring My Bell', CAST(8.99 AS Numeric(10, 2)));