
INSERT INTO  "artist" ("id", "name") VALUES (1, 'AC/DC');
INSERT INTO  "artist" ("id", "name") VALUES (2, 'Accept');
INSERT INTO  "artist" ("id", "name") VALUES (3, 'Aerosmith');
INSERT INTO  "artist" ("id", "name") VALUES (4, 'Alanis Morissette');
INSERT INTO  "artist" ("id", "name") VALUES (5, 'Alice In Chains');
INSERT INTO  "artist" ("id", "name") VALUES (6, 'Antônio Carlos Jobim');
INSERT INTO  "artist" ("id", "name") VALUES (7, 'Apocalyptica');
INSERT INTO  "artist" ("id", "name") VALUES (8, 'Audioslave');
INSERT INTO  "artist" ("id", "name") VALUES (10, 'Billy Cobham');
INSERT INTO  "artist" ("id", "name") VALUES (11, 'Black Label Society');
INSERT INTO  "artist" ("id", "name") VALUES (12, 'Black Sabbath');
INSERT INTO  "artist" ("id", "name") VALUES (14, 'Bruce Dickinso');
INSERT INTO  "artist" ("id", "name") VALUES (15, 'Buddy Guy');
INSERT INTO  "artist" ("id", "name") VALUES (16, 'Caetano Veloso');
INSERT INTO  "artist" ("id", "name") VALUES (17, 'Chico Buarque');
INSERT INTO  "artist" ("id", "name") VALUES (18, 'Chico Science & Nação Zumbi');
INSERT INTO  "artist" ("id", "name") VALUES (19, 'Cidade Negra');
INSERT INTO  "artist" ("id", "name") VALUES (20, 'Cláudio Zoli');
INSERT INTO  "artist" ("id", "name") VALUES (21, 'Various artists');
INSERT INTO  "artist" ("id", "name") VALUES (22, 'Led Zeppeli');
INSERT INTO  "artist" ("id", "name") VALUES (23, 'Frank Zappa & Captain Beefheart');
INSERT INTO  "artist" ("id", "name") VALUES (24, 'Marcos Valle');
INSERT INTO  "artist" ("id", "name") VALUES (27, 'Gilberto Gil');
INSERT INTO  "artist" ("id", "name") VALUES (37, 'Ed Motta');
INSERT INTO  "artist" ("id", "name") VALUES (41, 'Elis Regina');
INSERT INTO  "artist" ("id", "name") VALUES (42, 'Milton Nascimento');
INSERT INTO  "artist" ("id", "name") VALUES (46, 'Jorge Be');
INSERT INTO  "artist" ("id", "name") VALUES (50, 'Metallica');
INSERT INTO  "artist" ("id", "name") VALUES (51, 'Quee');
INSERT INTO  "artist" ("id", "name") VALUES (52, 'Kiss');
INSERT INTO  "artist" ("id", "name") VALUES (53, 'Spyro Gyra');
INSERT INTO  "artist" ("id", "name") VALUES (55, 'David Coverdale');
INSERT INTO  "artist" ("id", "name") VALUES (56, 'Gonzaguinha');
INSERT INTO  "artist" ("id", "name") VALUES (58, 'Deep Purple');
INSERT INTO  "artist" ("id", "name") VALUES (59, 'Santana');
INSERT INTO  "artist" ("id", "name") VALUES (68, 'Miles Davis');
INSERT INTO  "artist" ("id", "name") VALUES (72, 'Vinícius De Moraes');
INSERT INTO  "artist" ("id", "name") VALUES (76, 'Creedence Clearwater Revival');
INSERT INTO  "artist" ("id", "name") VALUES (77, 'Cássia Eller');
INSERT INTO  "artist" ("id", "name") VALUES (79, 'Dennis Chambers');
INSERT INTO  "artist" ("id", "name") VALUES (80, 'Djava');
INSERT INTO  "artist" ("id", "name") VALUES (81, 'Eric Clapto');
INSERT INTO  "artist" ("id", "name") VALUES (82, 'Faith No More');
INSERT INTO  "artist" ("id", "name") VALUES (83, 'Falamansa');
INSERT INTO  "artist" ("id", "name") VALUES (84, 'Foo Fighters');
INSERT INTO  "artist" ("id", "name") VALUES (86, 'Funk Como Le Gusta');
INSERT INTO  "artist" ("id", "name") VALUES (87, 'Godsmack');
INSERT INTO  "artist" ("id", "name") VALUES (88, 'Guns '' Roses');
INSERT INTO  "artist" ("id", "name") VALUES (89, 'Incognito');
INSERT INTO  "artist" ("id", "name") VALUES (90, 'Iron Maide');
INSERT INTO  "artist" ("id", "name") VALUES (92, 'Jamiroquai');
INSERT INTO  "artist" ("id", "name") VALUES (94, 'Jimi Hendrix');
INSERT INTO  "artist" ("id", "name") VALUES (95, 'Joe Satriani');
INSERT INTO  "artist" ("id", "name") VALUES (96, 'Jota Quest');
INSERT INTO  "artist" ("id", "name") VALUES (98, 'Judas Priest');
INSERT INTO  "artist" ("id", "name") VALUES (99, 'Legião Urbana');
INSERT INTO  "artist" ("id", "name") VALUES (100, 'Lenny Kravitz');
INSERT INTO  "artist" ("id", "name") VALUES (101, 'Lulu Santos');
INSERT INTO  "artist" ("id", "name") VALUES (102, 'Marillio');
INSERT INTO  "artist" ("id", "name") VALUES (103, 'Marisa Monte');
INSERT INTO  "artist" ("id", "name") VALUES (105, 'Men At Work');
INSERT INTO  "artist" ("id", "name") VALUES (106, 'Motörhead');
INSERT INTO  "artist" ("id", "name") VALUES (109, 'Mötley Crüe');
INSERT INTO  "artist" ("id", "name") VALUES (110, 'Nirvana');
INSERT INTO  "artist" ("id", "name") VALUES (111, 'O Terço');
INSERT INTO  "artist" ("id", "name") VALUES (112, 'Olodum');
INSERT INTO  "artist" ("id", "name") VALUES (113, 'Os Paralamas Do Sucesso');
INSERT INTO  "artist" ("id", "name") VALUES (114, 'Ozzy Osbourne');
INSERT INTO  "artist" ("id", "name") VALUES (115, 'Page & Plant');
INSERT INTO  "artist" ("id", "name") VALUES (117, 'Paul D''Ianno');
INSERT INTO  "artist" ("id", "name") VALUES (118, 'Pearl Jam');
INSERT INTO  "artist" ("id", "name") VALUES (120, 'Pink Floyd');
INSERT INTO  "artist" ("id", "name") VALUES (124, 'R.E.M.');
INSERT INTO  "artist" ("id", "name") VALUES (126, 'Raul Seixas');
INSERT INTO  "artist" ("id", "name") VALUES (127, 'Red Hot Chili Peppers');
INSERT INTO  "artist" ("id", "name") VALUES (128, 'Rush');
INSERT INTO  "artist" ("id", "name") VALUES (130, 'Skank');
INSERT INTO  "artist" ("id", "name") VALUES (132, 'Soundgarde');
INSERT INTO  "artist" ("id", "name") VALUES (133, 'Stevie Ray Vaughan & Double Trouble');
INSERT INTO  "artist" ("id", "name") VALUES (134, 'Stone Temple Pilots');
INSERT INTO  "artist" ("id", "name") VALUES (135, 'System Of A Dow');
INSERT INTO  "artist" ("id", "name") VALUES (136, 'Terry Bozzio, Tony Levin & Steve Stevens');
INSERT INTO  "artist" ("id", "name") VALUES (137, 'The Black Crowes');
INSERT INTO  "artist" ("id", "name") VALUES (139, 'The Cult');
INSERT INTO  "artist" ("id", "name") VALUES (140, 'The Doors');
INSERT INTO  "artist" ("id", "name") VALUES (141, 'The Police');
INSERT INTO  "artist" ("id", "name") VALUES (142, 'The Rolling Stones');
INSERT INTO  "artist" ("id", "name") VALUES (144, 'The Who');
INSERT INTO  "artist" ("id", "name") VALUES (145, 'Tim Maia');
INSERT INTO  "artist" ("id", "name") VALUES (150, 'U2');
INSERT INTO  "artist" ("id", "name") VALUES (151, 'UB40');
INSERT INTO  "artist" ("id", "name") VALUES (152, 'Van Hale');
INSERT INTO  "artist" ("id", "name") VALUES (153, 'Velvet Revolver');
INSERT INTO  "artist" ("id", "name") VALUES (155, 'Zeca Pagodinho');
INSERT INTO  "artist" ("id", "name") VALUES (157, 'Dread Zeppeli');
INSERT INTO  "artist" ("id", "name") VALUES (179, 'Scorpions');
INSERT INTO  "artist" ("id", "name") VALUES (196, 'Cake');
INSERT INTO  "artist" ("id", "name") VALUES (197, 'Aisha Duo');
INSERT INTO  "artist" ("id", "name") VALUES (200, 'The Posies');
INSERT INTO  "artist" ("id", "name") VALUES (201, 'Luciana Souza/Romero Lubambo');
INSERT INTO  "artist" ("id", "name") VALUES (202, 'Aaron Goldberg');
INSERT INTO  "artist" ("id", "name") VALUES (203, 'Nicolaus Esterhazy Sinfonia');
INSERT INTO  "artist" ("id", "name") VALUES (204, 'Temple of the Dog');
INSERT INTO  "artist" ("id", "name") VALUES (205, 'Chris Cornell');
INSERT INTO  "artist" ("id", "name") VALUES (206, 'Alberto Turco & Nova Schola Gregoriana');
INSERT INTO  "artist" ("id", "name") VALUES (208, 'English Concert & Trevor Pinnock');
INSERT INTO  "artist" ("id", "name") VALUES (211, 'Wilhelm Kempff');
INSERT INTO  "artist" ("id", "name") VALUES (212, 'Yo-Yo Ma');
INSERT INTO  "artist" ("id", "name") VALUES (213, 'Scholars Baroque Ensemble');
INSERT INTO  "artist" ("id", "name") VALUES (217, 'Royal Philharmonic Orchestra & Sir Thomas Beecham');
INSERT INTO  "artist" ("id", "name") VALUES (219, 'Britten Sinfonia, Ivor Bolton & Lesley Garrett');
INSERT INTO  "artist" ("id", "name") VALUES (221, 'Sir Georg Solti & Wiener Philharmoniker');
INSERT INTO  "artist" ("id", "name") VALUES (223, 'London Symphony Orchestra & Sir Charles Mackerras');
INSERT INTO  "artist" ("id", "name") VALUES (224, 'Barry Wordsworth & BBC Concert Orchestra');
INSERT INTO  "artist" ("id", "name") VALUES (226, 'Eugene Ormandy');
INSERT INTO  "artist" ("id", "name") VALUES (229, 'Boston Symphony Orchestra & Seiji Ozawa');
INSERT INTO  "artist" ("id", "name") VALUES (230, 'Aaron Copland & London Symphony Orchestra');
INSERT INTO  "artist" ("id", "name") VALUES (231, 'Ton Koopma');
INSERT INTO  "artist" ("id", "name") VALUES (232, 'Sergei Prokofiev & Yuri Temirkanov');
INSERT INTO  "artist" ("id", "name") VALUES (233, 'Chicago Symphony Orchestra & Fritz Reiner');
INSERT INTO  "artist" ("id", "name") VALUES (234, 'Orchestra of The Age of Enlightenment');
INSERT INTO  "artist" ("id", "name") VALUES (236, 'James Levine');
INSERT INTO  "artist" ("id", "name") VALUES (237, 'Berliner Philharmoniker & Hans Rosbaud');
INSERT INTO  "artist" ("id", "name") VALUES (238, 'Maurizio Pollini');
INSERT INTO  "artist" ("id", "name") VALUES (240, 'Gustav Mahler');
INSERT INTO  "artist" ("id", "name") VALUES (242, 'Edo de Waart & San Francisco Symphony');
INSERT INTO  "artist" ("id", "name") VALUES (244, 'Choir Of Westminster Abbey & Simon Presto');
INSERT INTO  "artist" ("id", "name") VALUES (245, 'Michael Tilson Thomas & San Francisco Symphony');
INSERT INTO  "artist" ("id", "name") VALUES (247, 'The King''s Singers');
INSERT INTO  "artist" ("id", "name") VALUES (248, 'Berliner Philharmoniker & Herbert Von Karaja');
INSERT INTO  "artist" ("id", "name") VALUES (250, 'Christopher O''Riley');
INSERT INTO  "artist" ("id", "name") VALUES (251, 'Fretwork');
INSERT INTO  "artist" ("id", "name") VALUES (252, 'Amy Winehouse');
INSERT INTO  "artist" ("id", "name") VALUES (253, 'Calexico');
INSERT INTO  "artist" ("id", "name") VALUES (255, 'Yehudi Menuhi');
INSERT INTO  "artist" ("id", "name") VALUES (258, 'Les Arts Florissants & William Christie');
INSERT INTO  "artist" ("id", "name") VALUES (259, 'The 12 Cellists of The Berlin Philharmonic');
INSERT INTO  "artist" ("id", "name") VALUES (260, 'Adrian Leaper & Doreen de Feis');
INSERT INTO  "artist" ("id", "name") VALUES (261, 'Roger Norrington, London Classical Players');
INSERT INTO  "artist" ("id", "name") VALUES (264, 'Kent Nagano and Orchestre de l''Opéra de Lyo');
INSERT INTO  "artist" ("id", "name") VALUES (265, 'Julian Bream');
INSERT INTO  "artist" ("id", "name") VALUES (266, 'Martin Roscoe');
INSERT INTO  "artist" ("id", "name") VALUES (267, 'Göteborgs Symfoniker & Neeme Järvi');
INSERT INTO  "artist" ("id", "name") VALUES (270, 'Gerald Moore');
INSERT INTO  "artist" ("id", "name") VALUES (271, 'Mela Tenenbaum, Pro Musica Prague & Richard Kapp');
INSERT INTO  "artist" ("id", "name") VALUES (274, 'Nash Ensemble');
INSERT INTO  "artist" ("id", "name") VALUES (276, 'Chic');
INSERT INTO  "artist" ("id", "name") VALUES (277, 'Anita Ward');
INSERT INTO  "artist" ("id", "name") VALUES (278, 'Donna Summer');
